In [1]:
import models
from models import get_raw_data, gerar_dataframe_classificacao

import pandas as pd

In [2]:
pasta = 'database/dados_tratados/harmonicos_1'
arquivo = 'Dados_Normalizados.csv'

In [3]:
df = get_raw_data.GetData(pasta,arquivo).GetDataframe()

In [4]:
df

,rotacao_hz,maximo,rms,assimetria,curtose,fator_crista,pot_ball_fault,pot_outer_race,pot_rotacao_hz,sensor,normal,desalinhamento_horizontal,desalinhamento_vertical,desbalanceamento,ball_fault,outer_race
0,0.00,0.282094,0.275661,0.466259,0.146040,0.341173,0.005802,0.004186,0.004077,0.0,1,0.0,0.0,0.0,0.0,0.0
1,0.00,0.332706,0.276122,0.467238,0.148418,0.466092,0.006144,0.003579,0.004078,0.0,1,0.0,0.0,0.0,0.0,0.0
2,0.00,0.332706,0.276035,0.463734,0.148229,0.466341,0.005770,0.003331,0.004263,0.0,1,0.0,0.0,0.0,0.0,0.0
3,0.00,0.359523,0.276068,0.479110,0.160277,0.533047,0.005814,0.003959,0.004161,0.0,1,0.0,0.0,0.0,0.0,0.0
4,0.00,0.359523,0.274593,0.476260,0.156181,0.537617,0.005772,0.003779,0.003671,0.0,1,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49603,0.95,1.420854,2.157980,0.081319,0.035974,0.094412,0.521079,0.339251,75.399603,1.0,0,0.0,0.0,0.0,0.0,35.0
49604,0.95,1.582628,2.152515,0.086307,0.037944,0.151765,0.340771,0.220798,74.728060,1.0,0,0.0,0.0,0.0,0.0,35.0
49605,0.95,1.582628,2.155161,0.086497,0.040828,0.151093,0.542961,0.296457,74.267885,1.0,0,0.0,0.0,0.0,0.0,35.0
49606,0.95,1.560321,2.158060,0.064818,0.044697,0.142641,0.358225,0.272909,74.105395,1.0,0,0.0,0.0,0.0,0.0,35.0
49607,0.95,1.600151,2.164308,0.085052,0.046138,0.154826,0.415253,0.358089,74.203646,1.0,0,0.0,0.0,0.0,0.0,35.0

In [5]:
df = gerar_dataframe_classificacao.GerarDataframe(df).Get()
df

,rotacao_hz,maximo,rms,assimetria,curtose,fator_crista,pot_ball_fault,pot_outer_race,pot_rotacao_hz,sensor,normal,desalinhamento_horizontal,desalinhamento_vertical,desbalanceamento,ball_fault,outer_race
0,0.00,0.282094,0.275661,0.466259,0.146040,0.341173,0.005802,0.004186,0.004077,0.0,sim,-,-,-,-,-
1,0.00,0.332706,0.276122,0.467238,0.148418,0.466092,0.006144,0.003579,0.004078,0.0,sim,-,-,-,-,-
2,0.00,0.332706,0.276035,0.463734,0.148229,0.466341,0.005770,0.003331,0.004263,0.0,sim,-,-,-,-,-
3,0.00,0.359523,0.276068,0.479110,0.160277,0.533047,0.005814,0.003959,0.004161,0.0,sim,-,-,-,-,-
4,0.00,0.359523,0.274593,0.476260,0.156181,0.537617,0.005772,0.003779,0.003671,0.0,sim,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49603,0.95,1.420854,2.157980,0.081319,0.035974,0.094412,0.521079,0.339251,75.399603,1.0,nao,-,-,-,-,alto
49604,0.95,1.582628,2.152515,0.086307,0.037944,0.151765,0.340771,0.220798,74.728060,1.0,nao,-,-,-,-,alto
49605,0.95,1.582628,2.155161,0.086497,0.040828,0.151093,0.542961,0.296457,74.267885,1.0,nao,-,-,-,-,alto
49606,0.95,1.560321,2.158060,0.064818,0.044697,0.142641,0.358225,0.272909,74.105395,1.0,nao,-,-,-,-,alto
49607,0.95,1.600151,2.164308,0.085052,0.046138,0.154826,0.415253,0.358089,74.203646,1.0,nao,-,-,-,-,alto

In [7]:
x = df[models.colunas_x]
y = df[models.defeitos_gerais]

In [25]:
x

,rotacao_hz,maximo,rms,assimetria,curtose,fator_crista,pot_ball_fault,pot_outer_race,pot_rotacao_hz,sensor
0,0.00,0.282094,0.275661,0.466259,0.146040,0.341173,0.005802,0.004186,0.004077,0.0
1,0.00,0.332706,0.276122,0.467238,0.148418,0.466092,0.006144,0.003579,0.004078,0.0
2,0.00,0.332706,0.276035,0.463734,0.148229,0.466341,0.005770,0.003331,0.004263,0.0
3,0.00,0.359523,0.276068,0.479110,0.160277,0.533047,0.005814,0.003959,0.004161,0.0
4,0.00,0.359523,0.274593,0.476260,0.156181,0.537617,0.005772,0.003779,0.003671,0.0
...,...,...,...,...,...,...,...,...,...,...
49603,0.95,1.420854,2.157980,0.081319,0.035974,0.094412,0.521079,0.339251,75.399603,1.0
49604,0.95,1.582628,2.152515,0.086307,0.037944,0.151765,0.340771,0.220798,74.728060,1.0
49605,0.95,1.582628,2.155161,0.086497,0.040828,0.151093,0.542961,0.296457,74.267885,1.0
49606,0.95,1.560321,2.158060,0.064818,0.044697,0.142641,0.358225,0.272909,74.105395,1.0
49607,0.95,1.600151,2.164308,0.085052,0.046138,0.154826,0.415253,0.358089,74.203646,1.0

In [26]:
y

,normal,desalinhamento_horizontal,desalinhamento_vertical,desbalanceamento,ball_fault,outer_race
0,sim,-,-,-,-,-
1,sim,-,-,-,-,-
2,sim,-,-,-,-,-
3,sim,-,-,-,-,-
4,sim,-,-,-,-,-
...,...,...,...,...,...,...
49603,nao,-,-,-,-,alto
49604,nao,-,-,-,-,alto
49605,nao,-,-,-,-,alto
49606,nao,-,-,-,-,alto
49607,nao,-,-,-,-,alto

In [9]:
# Importando as bibliotecas necessÃ¡rias
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


# Separando os dados em conjunto de treinamento e conjunto de teste
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# Criando o modelo de classificaÃ§Ã£o com o algoritmo Random Forest
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Treinando o modelo com os dados de treinamento
clf.fit(X_train, y_train)

# Fazendo previsÃµes com os dados de teste
y_pred = clf.predict(X_test)

In [14]:
y_p = pd.DataFrame(y_pred)
y_t = pd.DataFrame(y_test)

y_p.columns = y_t.columns

In [15]:
y_p

,normal,desalinhamento_horizontal,desalinhamento_vertical,desbalanceamento,ball_fault,outer_race
0,nao,-,-,alto,-,-
1,nao,-,-,baixo,-,-
2,nao,baixo,-,-,-,-
3,nao,-,-,medio,-,-
4,nao,-,-,alto,-,-
...,...,...,...,...,...,...
14878,nao,-,medio,-,-,-
14879,nao,-,-,baixo,-,-
14880,nao,-,baixo,-,-,-
14881,nao,-,-,alto,-,-
14882,sim,-,-,-,-,-

In [16]:
y_t

,normal,desalinhamento_horizontal,desalinhamento_vertical,desbalanceamento,ball_fault,outer_race
30130,nao,-,-,alto,-,-
19026,nao,-,alto,-,-,-
3502,nao,baixo,-,-,-,-
25663,nao,-,-,medio,-,-
20759,nao,-,-,baixo,-,-
...,...,...,...,...,...,...
12727,nao,-,medio,-,-,-
20164,nao,-,-,baixo,-,-
9899,nao,-,baixo,-,-,-
29803,nao,-,-,alto,-,-
1009,sim,-,-,-,-,-

In [20]:
results = []

# Loop para comparar linha por linha
for i in range(len(y_t)):
    results.append(y_t.iloc[i].equals(y_p.iloc[i]))

# Crie um novo DataFrame com os resultados
df_results = pd.DataFrame({'linha_identica': results})

print(df_results)

       linha_identica
0                True
1               False
2                True
3                True
4               False
...               ...
14878            True
14879            True
14880            True
14881            True
14882            True

[14883 rows x 1 columns]

In [21]:
df_true = df_results[df_results['linha_identica'] == True]
df_false = df_results[df_results['linha_identica'] == False]

In [22]:
df_true

       linha_identica
0                True
2                True
3                True
5                True
6                True
...               ...
14878            True
14879            True
14880            True
14881            True
14882            True

[13194 rows x 1 columns]

In [23]:
df_false

       linha_identica
1               False
4               False
13              False
31              False
35              False
...               ...
14815           False
14864           False
14867           False
14868           False
14877           False

[1689 rows x 1 columns]

In [24]:
acuracia = len(df_true)/(len(df_true)+len(df_false))
acuracia

0.8865148155613788